name: Günlük Commit

on:
  schedule:
    - cron: "30 12 * * *" 

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
    - name: Repo'yu Klonla
      uses: actions/checkout@v3

    - name: Dosyayı Güncelle
      run: echo "Güncelleme $(date)" >> log.txt

    - name: Commit ve Push
      run: |
        git config --global user.name "ahmetadsay"
        git config --global user.email "adsayahmet94@hotmail.com"
        git add .
        git commit -m "Günlük otomatik commit $(date)"
        git push
